default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { '5432' } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'uchi_internship_task_development' } %>

test:
  <<: *default
  database: uchi_internship_task_test

production:
  <<: *default
  database: uchi_internship_task_production
